### ISSUE TITLE
Teams page in an infinite redirect loop

### ISSUE THREAD

**Issue by IsmailM** [wurmlab/wurmlab.github.io#17]
[http://wurmlab.github.io/team](http://wurmlab.github.io/team) is loop infinitely for me…

Anyone else?

**Comment by yeban** [comment]
Same here.

**Comment by yannickwurm** [comment]
shit this is important

**Comment by yeban** [comment]
The site works fine locally. Something is wrong at Github's end?

Removing team.html file, which set a redirect to team/ seems to have fixed the issue. On production, my page (`team/priyam`) is also in redirect loop - both the pages had a foo.html file to redirect to foo/ using jekyll-redirectly plugin.

The redirect was setup to preserve the old team.html url. If this solution is not acceptable, I can revert the change.

**Comment by yeban** [comment]
Github has upgraded it's build system to Jekyll 3.0 - https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0. We use 2.x. I don't think we can control Jekyll version on production. While their post doesn't indicate redirect loop as an issue, it's possible that the jekyll-redirect-from plugin breaks with Jekyll 3.0 or due to some other change in Github-pages infrastructure.

**Comment by yannickwurm** [comment]
can't look in detail now
there are 2 manners of setting up redirect loops: one with an 'almost blank' file,  another is in the central config file
ideal would be to have the standard (302??) redirects...

**Comment by yannickwurm** [comment]
the proper way is (i think) with redirect-from in the frontmatter of the .md page  as here: 
  ab8ed70a43557c59134f69201f09ae0ffc3eabf3

**Comment by yannickwurm** [comment]
```
redirect_from:                     
  - /team.html 
```
