### ISSUE TITLE
pdf link missing on publication page but present in rubyscholarconfig.yaml

### ISSUE THREAD

**Issue by EmelineAurore** [wurmlab/wurmlab.github.io#46]
- "The Molecular Clockwork of the Fire Ant Solenopsis invicta" : "/publications/ingram2012-fireAntClockGenes.pdf"
- "Epigenetics: The Making of Ant Castes" : "/publications/2012CurrBiolAntepigenetics.pdf"
-   "Odorant Binding Proteins of the Red Imported Fire Ant, Solenopsis invicta: An Example of the Problems Facing the Analysis of Widely Divergent Proteins" : "/publications/gotzek2011obps.pdf"
-   "Behind the Scenes of an Ant Genome Project" : "/publications/wurm2011antGenomeBehindTheScenes.pdf"
-   "Parasitoid Wasps: From Natural History to Genomic Studies" : "/publications/wurm2010wasps.pdf"

**Comment by yeban** [comment]
I have added PDF links for these. As far as I can tell, rubyscholarconfig.yaml is not used for generating the site. It may have been used to generate an earlier version of the publications page; the page is manually updated now.

https://github.com/yannickwurm/rubyscholar is broken. Could be because of changes to Google Scholar's API, or because some edge cases (e.g., preprints) were never handled. It's probably worth trying to fix @yannickwurm's rubyscholar. I will be happy to look into that during a website hackathon. Alternatively, we can just remove citation count from publications page and auto-generate the rest similar to teams and tools page.

**Comment by yannickwurm** [comment]
Thanks priyam.

I am not sure that it is worth generating this whole page using rubyscholar (in part because even if parsing is perfect, Google Scholar truncates some information). However, I think we *will* need a way of updating citationcounts (but another way of doing this could be via an independent file, e.g. a json that we generate separately from a modified rubyscholar).

**Comment by IsmailM** [comment]
Hey guys, 

noticed u guys talking about this :)

See my fork for [rubyscholar](https://github.com/IsmailM/rubyscholar) - I worked on it a year ago:
 
```
# tested with ruby 2.3.3
# make a config.yaml with ur email in it (see example)
bundle exec rubyscholar scrape_to_json
```
It produces a json - with cross ref and google scholar output... (with citation counts & non-truncated info etc.)

It can be improved  - e.g. by integrating: ` bionode-ncbi search pubmed  "yannick wurm"` instead of google scholar for the DOIs to pass into crossref etc.

Feel free to fork my fork and fix it up...

**Comment by yeban** [comment]
Thanks @IsmailM. We pulled your changes into [yannickwurm/rubyscholar](https://github.com/yeban/rubyscholar.git). I will let you know if we/ I make further changes.
