### ISSUE TITLE
idea for blog post: the index/journal club system

### ISSUE THREAD

**Issue by EmelineAurore** [wurmlab/wurmlab.github.io#63]
@nat2bee asked me how the index/3-min journal club worked. I explained quickly, maybe other labs might want to read this too. We could write a short post about it, and share the R code as well.

**Comment by yannickwurm** [comment]
Yes good idea

**Comment by EmelineAurore** [comment]
Here is a draft, can someone review please?

## Keeping up with reading newly published articles

**What is it?**
We called it _the Index_, it is our monthly reading review, tailored to what we do and what we research.

**Why do you do it?**
There are so many articles being published as we speak, it is quite difficult to keep up with reading new material. We want to increase our general knowledge of important questions, techniques and discoveries in our greater field, while decreasing the likelihood of missing relevant "key paper". As social insect researchers, we are keen to efficiently helping each other out by sharing our readings. Finally, we are getting to read more broadly - including outside of our comfort zone.

**How does it work?**
Each month, each Wurmlab member gets a list of three journals to review, from our own journal generator. They read the previous month’s table of content and pick up the 3 articles that they think are relevant to the group/a person. We write it in a document that everyone can read at anytime.

**Great, where can I see an example?** 
See the last installment of the Index here [insert link to pdf of previous month].

**And where is your code?**
It’s on Github here [link to public script], and you’re welcome to fork it.

**Comment by ginobrignoli** [comment]
**Keeping up with reading newly published articles**

**What is it?**
We called it _the Index_, it is our monthly reading review, tailored to our areas of interest and research.

**Why do you do it?**
Because there are so many articles being published it can be quite difficult to keep up with reading new material. We want to increase our general knowledge of important questions, techniques and discoveries in our wider research areas while decreasing the likelihood of missing any relevant "key papers". We are also keen to efficiently help each other out by sharing our readings. Finally, we are getting to read more broadly - including topics outside our comfort zone.

**How does it work?**
Each month, each Wurmlab member gets a list of three journals to review from our own journal generator. The script is on Github here. Three articles that are relevant to the group or a particular lab member are picked form each journal's table of contents. These articles are added to a document that anyone in the lab group can read at any time.

**Great, where can I see an example?**
See the last instalment of the Index here.
